version: '2'
services:
    basketballoauth2-mysql:
        container_name: basketballoauth2-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/BasketballOauth2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=basketballoauth2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
